version: 0.2

env:
  secrets-manager:
    TEST_KEY: "in-house-library-secret-keys:TEST_KEY"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # ソースコードのclone実行
      - git clone https://github.com/yuks0810-dev/in-house-library-api.git
      - cd in-house-library-api
      - npm install
  pre_build:
    on-failure: ABORT
    commands:
      - echo Nothing to do in the pre_build phase...
      - echo "-------------------"
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo "$CODEBUILD_WEBHOOK_TRIGGER"
      - echo $TEST_KEY
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - echo $TEST_KEY
      - echo $CODEBUILD_WEBHOOK_TRIGGER
  post_build:
    on-failure: ABORT
    commands:
      - echo $TEST_KEY
      - echo Build completed on `date`