version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      # ソースコードのclone
      # CodePipeline経由で実行する場合には、cloneがスキップされる
      - git clone https://github.com/yuks0810-dev/in-house-library-api.git
      - cd in-house-library-api
      - npm install
  pre_build:
    on-failure: ABORT
    commands:
      - echo Nothing to do in the pre_build phase...
      - echo ${TEST_ENV}
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - echo ${TEST_ENV}
  post_build:
    on-failure: ABORT
    commands:
      - echo ${TEST_ENV}
      - echo Build completed on `date`