version: 0.2

env:
  secrets-manager:
    # key: secret-id:json-key:version-stage:version-id
    TEST_KEY: "in-house-library-secret-keys:TEST_KEY"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      # ソースコードのclone
      # CodePipeline経由で実行する場合には、cloneがスキップされる
      - git clone https://github.com/yuks0810-dev/in-house-library-api.git
      - cd in-house-library-api
      - npm install
  pre_build:
    on-failure: ABORT
    commands:
      - echo Nothing to do in the pre_build phase...
      - echo ${TEST_KEY}
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - echo ${TEST_KEY}
  post_build:
    on-failure: ABORT
    commands:
      - echo ${TEST_KEY}
      - echo Build completed on `date`