version: 0.2

env:
  secrets-manager:
    TEST_KEY: "in-house-library-secret-keys:TEST_KEY"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - git clone https://github.com/yuks0810-dev/in-house-library-api.git
      - cd in-house-library-api
      - npm install
  pre_build:
    on-failure: ABORT
    commands:
      - echo Nothing to do in the pre_build phase...
      - echo $AWS_REGION
      - echo $CODEBUILD_WEBHOOK_BASE_REF
      - echo $TEST_KEY
      - echo $ANDROID_HOME
      - echo $ANDROID_SDK_BUILD_TOOLS
      - echo $ANDROID_SDK_BUILD_TOOLS_28
      - echo $ANDROID_SDK_EXTRAS
      - echo $ANDROID_SDK_MANAGER_SHA256
      - echo $ANDROID_SDK_MANAGER_VER
      - echo $ANDROID_SDK_PLATFORM_TOOLS
      - echo $ANDROID_SDK_PLATFORM_TOOLS_28
      - echo $ANT_DOWNLOAD_SHA512
      - echo $ANT_VERSION
      - echo $AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
      - echo $AWS_DEFAULT_REGION
      - echo $AWS_EXECUTION_ENV
      - echo $AWS_REGION
      - echo $CODEBUILD_AGENT_ENDPOINT
      - echo $CODEBUILD_AUTH_TOKEN
      - echo $CODEBUILD_BMR_URL
      - echo $CODEBUILD_BUILD_ARN
      - echo $CODEBUILD_BUILD_ID
      - echo $CODEBUILD_BUILD_IMAGE
      - echo $CODEBUILD_BUILD_NUMBER
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - echo $CODEBUILD_BUILD_URL
      - echo $CODEBUILD_CI
      - echo $CODEBUILD_CONTAINER_NAME
      - echo $CODEBUILD_EXECUTION_ROLE_BUILD
      - echo $CODEBUILD_FE_REPORT_ENDPOINT
      - echo $CODEBUILD_GOPATH
      - echo $CODEBUILD_INITIATOR
      - echo $CODEBUILD_KMS_KEY_ID
      - echo $CODEBUILD_LAST_EXIT
      - echo $CODEBUILD_LOG_PATH
      - echo $CODEBUILD_PROJECT_UUID
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_REPO_URL
      - echo $CODEBUILD_SOURCE_VERSION
      - echo $CODEBUILD_SRC_DIR
      - echo $CODEBUILD_START_TIME
      - echo $CODEBUILD_VPC_AZ
      - echo $CTS_LINK_LOCAL_ADDR
      - echo $DEBIAN_FRONTEND
      - echo $DIND_COMMIT
      - echo $DOCKER_BUCKET
      - echo $DOCKER_CHANNEL
      - echo $DOCKER_COMPOSE_VERSION
      - echo $DOCKER_SHA256
      - echo $DOCKER_VERSION
      - echo $DOTNET_31_SDK_VERSION
      - echo $ECS_CONTAINER_METADATA_URI
      - echo $FE_REPORT_LINK_LOCAL_ADDR
      - echo $GITVERSION_VERSION
      - echo $GOENV_DISABLE_GOPATH
      - echo $GOLANG_12_VERSION
      - echo $GOLANG_13_VERSION
      - echo $GOLANG_14_VERSION
      - echo $GOPATH
      - echo $GRADLE_DOWNLOADS_SHA256
      - echo $GRADLE_PATH
      - echo $GRADLE_VERSION
      - echo $HOME
      - echo $HOSTNAME
      - echo $INSTALLED_GRADLE_VERSIONS
      - echo $JAVA_11_HOME
      - echo $JAVA_8_HOME
      - echo $JAVA_HOME
      - echo $JDK_11_HOME
      - echo $JDK_8_HOME
      - echo $JDK_DOWNLOAD_SHA256
      - echo $JDK_DOWNLOAD_TAR
      - echo $JDK_HOME
      - echo $JRE_11_HOME
      - echo $JRE_8_HOME
      - echo $JRE_HOME
      - echo $MAVEN_DOWNLOAD_SHA512
      - echo $MAVEN_HOME
      - echo $MAVEN_OPTS
      - echo $MAVEN_VERSION
      - echo $NODE_10_VERSION
      - echo $NODE_12_VERSION
      - echo $NUGET_XMLDOC_MODE
      - echo $N_SRC_DIR
      - echo $OLDPWD
      - echo $PATH
      - echo $PHP_73_VERSION
      - echo $PHP_74_VERSION
      - echo $POWERSHELL_DOWNLOAD_SHA
      - echo $POWERSHELL_DOWNLOAD_URL
      - echo $POWERSHELL_VERSION
      - echo $PWD
      - echo $PYTHON_37_VERSION
      - echo $PYTHON_38_VERSION
      - echo $PYTHON_PIP_VERSION
      - echo $RBENV_SRC_DIR
      - echo $RUBY_26_VERSION
      - echo $RUBY_27_VERSION
      - echo $RUBY_BUILD_SRC_DIR
      - echo $SBT_VERSION
      - echo $SRC_DIR
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - echo $TEST_KEY
      - echo $CODEBUILD_WEBHOOK_TRIGGER
  post_build:
    on-failure: ABORT
    commands:
      - echo $TEST_KEY
      - echo Build completed on `date`